---
- name: Deploy Dynatrace OneAgent
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Ensure the required tools are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - tar

    - name: Download Dynatrace OneAgent installer
      get_url:
        url: "{{ dynatrace_installer_url }}"
        dest: /tmp/Dynatrace-OneAgent.sh
        mode: '0755'

    - name: Run the Dynatrace OneAgent installer
      command: "/bin/bash /tmp/Dynatrace-OneAgent.sh {{ monitoring_mode }} APP_LOG_CONTENT_ACCESS=1"

    - name: Verify OneAgent service is running
      service:
        name: oneagent
        state: started
        enabled: yes

    - name: Clean up installer script
      file:
        path: /tmp/Dynatrace-OneAgent.sh
        state: absent
